services:
  #frontend:
    #container_name: frontend
    #build:
      #context: .
      #dockerfile: packages/frontend/Dockerfile
    #ports:
      #- '3000:80' # Expose the UI app on port 3000
    #networks:
      #- app-network
    #depends_on:
      #- server
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    command: yarn nx start server
    ports:
      - '4000:3000' # Expose the backend on port 4000
    depends_on:
      - db
    environment:
      PORT: 3000
      APP_SECRET: 'asasasasa'
      PG_DATABASE_URL: postgres://yaari:yaari@db:5432/yaariapi
      WEBSOCKET_PORT: 4000
      FRONTEND_URL: 'http://localhost:5173'
      SERVER_URL: 'localhost:3000'
      BACKEND_URL: 'http://localhost:3000'
      IS_MULTIWORKSPACE_ENABLED: true
      GOOGLE_AUTH_ENABLED: false
      GOOGLE_AUTH_CLIENT_ID: 
      GOOGLE_AUTH_CLIENT_SECRET: 
      GOOGLE_AUTH_CALLBACK_URL: http://localhost:3000/google/auth/redirect
      GOOGLE_AUTH_APIS_CALLBACK_URL: http://localhost:3001/auth/google-apis/get-access-token
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - ./docker-postgres-multiple-dbs.sh:/docker-entrypoint-initdb.d/docker-postgres-multiple-dbs.sh
    environment:
      POSTGRES_USER: yaari
      POSTGRES_PASSWORD: yaari
      POSTGRES_DB_NAMES: yaariapi

networks:
  app-network:
    driver: bridge
